version: "3.8"
services:
 pessoas-api:
    image: ${DOCKER_REGISTRY-}pessoas-api
    env_file:
      - .env
    build:
      context: ./pessoas-api
      dockerfile: Dockerfile
    networks:
      - "pessoas-api-network"
    ports:
      - ${APP_PORT}:80
    expose:
      - ${APP_PORT}
    depends_on:
      - db

 db:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    networks:
      - "pessoas-api-network"

networks:
  pessoas-api-network:
    driver: bridge